cluster_name = "local-cluster"
location = "local-2"
server_id = 2
read_ratio = 0.25
local_deployment = true
scheduled_start_utc_ms = SCHEDULE

[[request_rate_intervals]]
duration_sec = 5
requests_per_sec = 10
read_ratio = 0.25

[[request_rate_intervals]]
duration_sec = 10
requests_per_sec = 1
read_ratio = 0.25

