location = "local-2"
server_id = 2
server_address = "127.0.0.1:8002"
read_ratio = 0.25
#kill_signal_sec = 0
#next_server = 1
summary_filepath = "./logs/client-2.json"
output_filepath = "./logs/client-2.csv"

[[requests]]
duration_sec = 5
requests_per_sec = 10
read_ratio = 0.25

[[requests]]
duration_sec = 10
requests_per_sec = 1
read_ratio = 0.25

