x-common-variables: &common-server-variables
  RUST_LOG: "debug"
  SERVER_CONFIG_FILE: "/app/server-config.toml"
  CLUSTER_CONFIG_FILE: "/app/cluster-config.toml"
  AUTOQUORUM_NODE_ADDRS: "s1:8000,s2:8000,s3:8000" # Overwrite node_addrs in cluster config TOML
  AUTOQUORUM_LISTEN_ADDRESS: "0.0.0.0"             # Overwrite listen_address in server config TOMLs
  AUTOQUORUM_LISTEN_PORT: 8000                     # Overwrite listen_port in server config TOMLs

services:
  s1:
    image: omnipaxos-server
    build:
      context: ./..
      dockerfile: server.dockerfile
    container_name: s1
    environment:
      <<: *common-server-variables
    volumes:
      - ./server-1-config.toml:/app/server-config.toml
      - ./cluster-config.toml:/app/cluster-config.toml
      - ./logs/:/app/logs/
  s2:
    image: omnipaxos-server
    container_name: s2
    environment:
      <<: *common-server-variables
    volumes:
      - ./server-2-config.toml:/app/server-config.toml
      - ./cluster-config.toml:/app/cluster-config.toml
      - ./logs/:/app/logs/
  s3:
    image: omnipaxos-server
    container_name: s3
    environment:
      <<: *common-server-variables
    volumes:
      - ./server-3-config.toml:/app/server-config.toml
      - ./cluster-config.toml:/app/cluster-config.toml
      - ./logs/:/app/logs/
  c1:
    image: omnipaxos-client
    build:
      context: ./..
      dockerfile: client.dockerfile
    container_name: c1
    environment:
      RUST_LOG: "debug"
      CONFIG_FILE: "/app/client-config.toml"
      AUTOQUORUM_SERVER_ADDRESS: "s1:8000" # Overwrite server_address in client config TOML
    volumes:
      - ./client-1-config.toml:/app/client-config.toml
      - ./logs/:/app/logs/
  c2:
    image: omnipaxos-client
    container_name: c2
    environment:
      RUST_LOG: "debug"
      CONFIG_FILE: "/app/client-config.toml"
      AUTOQUORUM_SERVER_ADDRESS: "s2:8000" # Overwrite server_address in client config TOML
    volumes:
      - ./client-2-config.toml:/app/client-config.toml
      - ./logs/:/app/logs/
