location = "local-2"
server_id = 2
num_clients = 1
output_filepath = "../benchmarks/logs/local-run/server-2.json"
# Cluster-wide settings
local_deployment = true
cluster_name = "local-cluster"
nodes = [1, 2, 3]
initial_leader = 1
initial_flexible_quorum = { read_quorum_size = 2, write_quorum_size = 2 }
optimize = false
optimize_threshold = 0.97
initial_read_strat = ["ReadAsWrite", "ReadAsWrite", "ReadAsWrite"]
